ThingsToReturn/Models/Offer.cs
namespace ThingsToReturn.Models
{
    public class Offer
    {
        public int Id { get; set; }
        
        [MaxLength(40, ErrorMessage ="Maximum 40 characters allowed")]
        [MinLength(8, ErrorMessage = "Minimum 8 characters required")]
        public string Name { get; set; }
        public string ImagePath { get; set; }
        
        [MaxLength(245, ErrorMessage = "Maximum 200 characters allowed")]
        [MinLength(8, ErrorMessage = "Minimum 8 characters required")]
        public string Description { get; set; }
        public Address Address { get; set; }
        
        [Column(TypeName="Date")]
        [DataType("Date")]
        public DateTime CreatedDate { get; set; }
        
        [Column(TypeName = "Date")]
        [DataType("Date")]
        public DateTime ExpirationDate { get; set; }
        public AppUser User { get; set; }
        public ICollection<AppUserOffer>? AppUserOffers { get; set; }
        public ICollection<OfferCategory>? OfferCategories { get; set; }
        
        public string? BookingId { get; set; }

    }
}

ThingsToReturn/Pages/Offers/AddOffer.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Security.Claims;

namespace ThingsToReturn.Pages
{
    [BindProperties]
    [Authorize]
    public class AddOfferModel : PageModel
    {
        private readonly ILogger<AddOfferModel> _logger;
        private readonly ICategoryService _categoryService;
        private readonly IOfferCategoryService _offercategoryservice;
        private readonly IOfferService _offerService;
        private readonly IAppUserService _appUserService;

        public Address Address { get; set; }
        public IFormFile ImageFile { get; set; }
        public IList<int> Categories { get; set; }
        public Offer Offer { get; set; }
        public CategoryToListVM CategoryList { get; set; }

        public AddOfferModel(ILogger<AddOfferModel> logger, ICategoryService categoryService,
            IOfferCategoryService offercategoryservice, IOfferService offerService, IAppUserService appUserService)
        {
            _logger = logger;
            _categoryService = categoryService;
            _offercategoryservice = offercategoryservice;
            _offerService = offerService;
            _appUserService = appUserService;
        }
        public void OnGet()
        {
            CategoryList = _categoryService.GetAllCategories();

        }

        public IActionResult OnPost()
        {

            CategoryList = _categoryService.GetAllCategories();

            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            _offercategoryservice.AddOffersWithCategories(Offer, ImageFile, Address, claim, Categories);

            return RedirectToPage("/Offers/Offers");
        }
    }
}

ThingsToReturn/Pages/Offers/ConfirmFollowOffer.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Security.Claims;

namespace ThingsToReturn.Pages
{
    [BindProperties]
    [Authorize]
    public class ConfirmFollowOfferModel : PageModel
    {
        private readonly IOfferService _offerService;
        private readonly IAppUserOfferService _appuserOfferService;

        public Offer Offer { get; set; }

        public ConfirmFollowOfferModel(IOfferService offerService, IAppUserOfferService appUserOfferService)
        {
            _offerService = offerService;
            _appuserOfferService = appUserOfferService;
        }
        public void OnGet(int id)
        {
            if (id != 0)
            {
                Offer = _offerService.GetOffer(id);
            }
        }   

        public IActionResult OnPost()
        {
            var offer = _offerService.GetOffer(Offer.Id);
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            if (Offer.Id != 0)
            {
                if(_appuserOfferService.IsFollowed(claim.Value, offer))
                {
                    TempData["followed"] = "You already follow this ad";
                    return RedirectToPage("/Offers/Offers");
                }
                _appuserOfferService.AddFollowOffer(claim?.Value, offer);
            }

            return RedirectToPage("/Offers/Offers");
        }
    }
}

ThingsToReturn/Pages/Offers/Delete.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Security.Claims;

namespace ThingsToReturn.Pages
{
    [BindProperties]
    [Authorize]
    public class DeleteOfferModel : PageModel
    {
        private readonly IOfferService _offerService;
        public Offer Offer { get; set; }

        public DeleteOfferModel(IOfferService offerService)
        {
            _offerService = offerService;
        }
        public void OnGet(int id)
        {
            if (id != 0)
            {
                Offer = _offerService.GetOffer(id);

            }
            
        }   

        public IActionResult OnPost()
        {
            if(Offer.Id != 0)
                _offerService.RemoveOffer(Offer);
             
            return RedirectToPage("/Offers/UsersOffers");
        }
    }
}

ThingsToReturn/Pages/Offers/FollowedOffers.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Security.Claims;

namespace ThingsToReturn.Pages
{
    [BindProperties]
    [Authorize]
    public class FolloweOffersModel : PageModel
    {
        private readonly ILogger<FolloweOffersModel> _logger;
        private readonly ICategoryService _categoryService;
        private readonly IOfferCategoryService _offercategoryservice;
        private readonly IOfferService _offerService;
        private readonly IAddressService _addressservice;
     
        public OfferToListVM OfferList { get; set; }
      

        public FolloweOffersModel(ILogger<FolloweOffersModel> logger, ICategoryService categoryService,
            IOfferCategoryService offercategoryservice, IOfferService offerService, IAddressService addressService)
        {
            _logger = logger;
            _categoryService = categoryService;
            _offercategoryservice = offercategoryservice;
            _offerService = offerService;
            _addressservice = addressService;
        }
        public void OnGet()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claims = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            OfferList = _offerService.GetFollowedOffers(claims);
        }

        public IActionResult OnPostSelect()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claims = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            OfferList = _offerService.GetFollowedOffers(claims);
            return Page();
        }
    }
}

ThingsToReturn/Pages/Offers/MonitorOffer.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Security.Claims;

namespace ThingsToReturn.Pages
{
    [BindProperties]
    [Authorize]
    public class MonitorOfferModel : PageModel
    {
        private readonly IOfferService _offerService;
        public Offer Offer { get; set; }

        public MonitorOfferModel(IOfferService offerService)
        {
            _offerService = offerService;
        }
        public void OnGet(int id)
        {
            Offer = _offerService.GetOfferToDel(id);
        }   

        public IActionResult OnPost()
        {

            _offerService.RemoveOffer(Offer);
            return RedirectToPage("/Offers/UsersOffers");
        }
    }
}

ThingsToReturn/Pages/Offers/Offers.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Security.Claims;

namespace ThingsToReturn.Pages
{
    [BindProperties]
    public class OffersModel : PageModel
    {
        private readonly ILogger<OffersModel> _logger;
        private readonly ICategoryService _categoryService;
        private readonly IOfferCategoryService _offercategoryservice;
        private readonly IOfferService _offerService;
        private readonly IAddressService _addressservice;
        public string UserId { get; private set; }
        public CategoryToListVM CategoryList { get; set; }
        public OfferToListVM OfferList { get; set; }
        public List<string> cities { get; set; }
        public FilterModel FilterChoices { get; set; }

        public OffersModel(ILogger<OffersModel> logger, ICategoryService categoryService,
            IOfferCategoryService offercategoryservice, IOfferService offerService, IAddressService addressService)
        {
            _logger = logger;
            _categoryService = categoryService;
            _offercategoryservice = offercategoryservice;
            _offerService = offerService;
            _addressservice = addressService;
        }
        public void OnGet()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            UserId = claim?.Value;

            OfferList = _offerService.GetAllOffers();
            CategoryList = _categoryService.GetAllCategories();
            cities = _addressservice.GetAllCities();
        }

        public IActionResult OnPostSelect()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            UserId = claim?.Value;

            CategoryList = _categoryService.GetAllCategories();
            cities = _addressservice.GetAllCities();

                OfferList = _offerService.FiltrateOffers(FilterChoices);
            return Page();
        }
    }
}

ThingsToReturn/Pages/Offers/Reserve.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Security.Claims;

namespace ThingsToReturn.Pages
{
    [Authorize]
    [BindProperties]
    public class ReserveOfferModel : PageModel
    {
        private readonly IOfferService _offerService;
        private readonly IAppUserService _appUserService;
        public Offer Offer { get; set; }
        public Reservation Reservation { get; set; }
        public AppUserToListVM InterestedUsers { get; set; }
        public ReserveOfferModel(IOfferService offerService, IAppUserService appUserService)
        {
            _offerService = offerService;
            _appUserService = appUserService;
        }
        public void OnGet(int id)
        {


            if (id != 0)
            {
                Offer = _offerService.GetOffer(id);
                InterestedUsers = _appUserService.GetInterestedUsers(Offer.Id);
            }
            
        }   

        public IActionResult OnPostReserve()
        {
           
            _offerService.ReserveOffer(Reservation.UserId, Reservation.OfferId);
                 
            return RedirectToPage("/Offers/UsersOffers");
        }

        public IActionResult OnPostCancel()
        {
            
            _offerService.CancelReservation(Reservation.OfferId);
            
            return RedirectToPage("/Offers/UsersOffers");
        }
    }
}

ThingsToReturn/Pages/Offers/UnfollowOffer.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Security.Claims;

namespace ThingsToReturn.Pages
{
    [BindProperties]
    [Authorize]
    public class UnfollowOfferModel : PageModel
    {
        private readonly IOfferService _offerService;
        private readonly IAppUserOfferService _appUserOfferService;
        public Offer Offer { get; set; }

        public UnfollowOfferModel(IOfferService offerService, IAppUserOfferService appUserOfferService)
        {
            _offerService = offerService;
            _appUserOfferService = appUserOfferService;
        }
        public void OnGet(int id)
        {
            if (id != 0)
            {
                Offer = _offerService.GetOffer(id);
            }
        }   

        public IActionResult OnPost()
        {

            var offer = _offerService.GetOffer(Offer.Id);
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            _appUserOfferService.RemoveFollowOffer(claim.Value, offer);
            

            return RedirectToPage("/Offers/FollowedOffers");
        }
    }
}

ThingsToReturn/Pages/Offers/UsersOffers.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Security.Claims;

namespace ThingsToReturn.Pages
{
    [BindProperties]
    [Authorize]
    public class UsersOfffers : PageModel
    {
        private readonly IOfferService _offerService;
        public OfferToListVM OfferList { get; set; }

        public UsersOfffers(ILogger<UsersOfffers> logger, IOfferService offerService)
        {
            _offerService = offerService;
        }
        public void OnGet()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            OfferList = _offerService.GetUsersOffers(claim);
        }

        public IActionResult OnPost()
        {
            return Page();
        }
    }
}

ThingsToReturn/Pages/Offers/AddOffer.cshtml
@page
@model ThingsToReturn.Pages.AddOfferModel
@{
}

<div class="mt-4">
    <h2>Add your advertisement</h2>
</div>

<form method="post" enctype="multipart/form-data">
    
    <div class="form-group">
        <label asp-for="Offer.Name" class="form-label mt-4">Name</label>
        <input asp-for="Offer.Name" type="text" class="form-control" id="" placeholder="Enter the name of your offer">
        <span asp-validation-for="Offer.Name" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Categories" class="form-label mt-4">Categories</label>
        <select asp-for="Categories" multiple class="form-control" id="" size="3">
            @foreach(var category in Model.CategoryList.Categories)
            {
                <option value="@category.Id">@category.Name</option>
            }
        </select>
        <span asp-validation-for="Categories" class="text-danger"></span>
    </div>

    <div class="form-group">
      <input asp-for="ImageFile" accept="image/jpg,image/jpeg,image/png" class="form-control mt-4" placeholder="xd">
      <span asp-validation-for="ImageFile" lang="en-gb" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Offer.ExpirationDate" class="form-label mt-4">Expiration date from</label>
        <input asp-for="Offer.ExpirationDate" class="form-control"/>
        <span asp-validation-for="Offer.ExpirationDate" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Offer.Description" class="form-label mt-4"></label>
        <textarea asp-for="Offer.Description" class="form-control" rows="7" placeholder="Describe your offer"></textarea>
        <span asp-validation-for="Offer.Description" class="text-danger"></span>
    </div>
    <div class="form-group" style="margin-top: 10px">
        <label asp-for="Address.Country" class="form-label mt-2"></label>
        <input asp-for="Address.Country" class="form-control"  aria-required="true" required/>
        <span asp-validation-for="Address.Country" class="text-danger"></span>
    </div>
    <div class="form-group" style="margin-top: 10px">
        <label asp-for="Address.City" class="form-label mt-2"></label>
        <input asp-for="Address.City" class="form-control" aria-required="true" required/>
        <span asp-validation-for="Address.City" class="text-danger"></span>
    </div>
    <div class="form-group" style="margin-top: 10px">
        <label asp-for="Address.ZipCode" class="form-label mt-2"></label>
        <input asp-for="Address.ZipCode" class="form-control"  aria-required="true" required/>
        <span asp-validation-for="Address.ZipCode" class="text-danger"></span>
    </div>
    <div class="form-group" style="margin-top: 10px">
        <label asp-for="Address.Street" class="form-label mt-2"></label>
        <input asp-for="Address.Street" class="form-control"  aria-required="true" required/>
        <span asp-validation-for="Address.Street" class="text-danger"></span>
    </div>
    <div class="form-group" style="margin-top: 10px">
        <label asp-for="Address.BuildingNr" class="form-label mt-2"></label>
        <input asp-for="Address.BuildingNr" class="form-control"  aria-required="true" required/>
        <span asp-validation-for="Address.BuildingNr" class="text-danger"></span>
    </div>
    <div class="form-group" style="margin-top: 10px">
        <label asp-for="Address.ApartmentNr" class="form-label mt-2"></label>
        <input asp-for="Address.ApartmentNr" class="form-control" aria-required="true" required />
        <span asp-validation-for="Address.ApartmentNr" class="text-danger"></span>
    </div>
    <div class="form-group">
        <button class="btn btn-primary mt-4" type="submit">Add</button>
    </div>
</form>

@section Scripts
{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

ThingsToReturn/Pages/Offers/ConfirmFollowOffer.cshtml
@page
@model ThingsToReturn.Pages.ConfirmFollowOfferModel
@{
}
<div class="text-center">
    <form method="post">
        <input hidden asp-for="Offer.Id" />
        <div class ="border p-3 mt-4">
            <div class="row pb-2">
                <h2 class="text-primary pl-3">Follow advertisement</h2> 
                <hr />
            </div>
            <div class="mb-3">
                <label asp-for="Offer.Name"></label>
                <input asp-for="Offer.Name" disabled class="form-control"/>
            </div>               
            <div class="mb-3">  
                <label asp-for="Offer.Description" ></label>
                <input asp-for="Offer.Description" disabled class="form-control"/>
            </div>
            <div class="mb-3">  
                <label asp-for="Offer.CreatedDate" ></label>
                <input asp-for="Offer.CreatedDate" disabled class="form-control"/>
            </div>
            <div class="mb-3">  
                <label asp-for="Offer.ExpirationDate" ></label>
                <input asp-for="Offer.ExpirationDate" disabled class="form-control"/>
            </div>
            
            @*
             <div class="mb-3">  
                <label asp-for="" ></label>
                <input asp-for="" disabled class="form-control"/>
            </div>
            <div class="mb-3">  
                <label asp-for="" ></label>
                <input asp-for="" disabled class="form-control"/>
            </div>*@

            <button type="submit" class="btn btn-success" style="width:150px">Follow</button>
            <a asp-page="/Offers/Offers" class="btn btn-secondary" style="width:150px">Back to ads</a>
        </div>
    </form>
</div>

ThingsToReturn/Pages/Offers/Delete.cshtml
@page
@model ThingsToReturn.Pages.DeleteOfferModel
@{
}
<div class="text-center">
    <form method="post">
        <input hidden asp-for="Offer.Id" />
        <div class ="border p-3 mt-4">
            <div class="row pb-2">
                <h2 class="text-primary pl-3">Delete Category</h2> 
                <hr />
            </div>
            <div class="mb-3">
                <label asp-for="Offer.Name"></label>
                <input asp-for="Offer.Name" disabled class="form-control"/>
            </div>               
            <div class="mb-3">  
                <label asp-for="Offer.Description" ></label>
                <input asp-for="Offer.Description" disabled class="form-control"/>
            </div>
            <div class="mb-3">  
                <label asp-for="Offer.CreatedDate" ></label>
                <input asp-for="Offer.CreatedDate" disabled class="form-control"/>
            </div>
            <div class="mb-3">  
                <label asp-for="Offer.ExpirationDate" ></label>
                <input asp-for="Offer.ExpirationDate" disabled class="form-control"/>
            </div>
            
            @*
             <div class="mb-3">  
                <label asp-for="" ></label>
                <input asp-for="" disabled class="form-control"/>
            </div>
            <div class="mb-3">  
                <label asp-for="" ></label>
                <input asp-for="" disabled class="form-control"/>
            </div>*@

            <button type="submit" class="btn btn-danger" style="width:150px">Delete</button>
            <a asp-page="/Offers/UsersOffers" class="btn btn-secondary" style="width:150px">Back to my ads</a>
        </div>
    </form>
</div>

ThingsToReturn/Pages/Offers/FollowedOffers.cshtml
@page
@model ThingsToReturn.Pages.FolloweOffersModel
@{
}


 
<h2 class="card-body">We found @Model.OfferList.Count advertisements</h2>
<div class="grid-offers-container">
    @foreach(var offer in Model.OfferList.Offers)
    {
        <div class="offers-row-grid-box-user" >
            <div  class="img-user">
               <img src="@offer.ImagePath" />
            </div>
            <div  class="loc-div ">
                <p class="card-body">
                    @offer.AddressVM.City
                </p>
            </div>
            <div class="row-box-1">
               <h6 class="card-header"> @(offer.Name)</h6>
            </div>
            <div class="row-box-2">
                <p >
                   @offer.Description
                </p>
            </div>
            <div class="button-follow">
                <a asp-page="/Offers/UnfollowOffer" asp-route-id="@offer.Id" class="btn btn-info">Unfollow</a>
            </div>
        </div>
    }
</div>

ThingsToReturn/Pages/Offers/ObservedOffers.cshtml
@page
@model ThingsToReturn.Pages.UsersOffersModel
@{
}

<h2 class="card-body">You have @Model.OfferList.Count advertisements</h2>
<div class="grid-offers-container">
    @foreach(var offer in Model.OfferList.Offers)
    {
        <div class="offers-row-grid-box-user" >
            <div  class="img-user">
               <img src="@offer.ImagePath" />
            </div>
            <div class="row-box-1">
               <h6 class="card-header"> @(offer.Name)</h6>
            </div>
            <div class="row-box-2">
                <p >
                   @offer.Description
                </p>
            </div>
            <div class="button-del">
                <a asp-page="/Offers/MonitorOffer" asp-route-id="@offer.Id" class="btn btn-primary">Delete</a>
            </div>
        </div>
    }
</div>

ThingsToReturn/Pages/Offers/Offers.cshtml
@page
@model ThingsToReturn.Pages.OffersModel
@if(TempData["followed"] is not null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>  
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["followed"]');
    </script> 

}


 <form class="row g-3 align-items-md-start" method="post" asp-page-handler="select">
    <div class="col-md-2">
        <label asp-for="FilterChoices.Name" class="form-label mt-4">Name</label>
        <input asp-for="FilterChoices.Name" class="form-control"/>
    </div>
    <div class="col-md-2">
        <label asp-for="FilterChoices.City" class="form-label mt-4">Cities</label>
        <select asp-for="FilterChoices.City" class="form-control">
            <option></option>
            @foreach(var city in Model.cities)
            {
                <option value="@city">@city</option>
            }    
        </select>
        <span asp-validation-for="FilterChoices.City" class="text-danger"></span>
    </div>
   <div class="col-md-2">
        <label asp-for="FilterChoices.CategoryId" class="form-label mt-4">Categories</label>
        <select asp-for="FilterChoices.CategoryId" class="form-control">
            <option selected></option>
            @foreach(var category in Model.CategoryList.Categories)
            {
                <option value="@category.Id">@category.Name</option>
            }
        </select>
        <span asp-validation-for="FilterChoices.CategoryId" class="text-danger"></span>
    </div>
    <div  class="axis main-axis">
        <button class="btn btn-primary " type="submit">Szukaj</button>
    </div>
    <hr />
</form>

<h2 class="card-body">We found @Model.OfferList.Count advertisements</h2>
<div class="grid-offers-container">
    @foreach(var offer in Model.OfferList.Offers)
    {
        <div class="offers-row-grid-box-user" >
            <div  class="img-user">
               <img src="@offer.ImagePath" />
            </div>
            <div  class="loc-div ">
                <p class="card-body">
                    @offer.AddressVM.City
                </p>
            </div>
            <div class="row-box-1">
               <h6 class="card-header"> @(offer.Name)</h6>
            </div>
            <div class="row-box-2">
                <p >
                   @offer.Description
                </p>
            </div>

            @if(offer.UserVM.Id != Model.UserId && Model.UserId is not null)
            {
                
            <div class="button-follow">
                <a asp-page="/Offers/ConfirmFollowOffer" asp-route-id="@offer.Id" class="btn btn-success">Follow</a>
            </div>
            }
            @if(offer.IsReservated)
            {
                <div class="icon-container">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16"% height="16" fill="currentColor" class="bi bi-book-fill" viewBox="0 0 16 16">
                        <path d="M8 1.783C7.015.936 5.587.81 4.287.94c-1.514.153-3.042.672-3.994 1.105A.5.5 0 0 0 0 2.5v11a.5.5 0 0 0 .707.455c.882-.4 2.303-.881 3.68-1.02 1.409-.142 2.59.087 3.223.877a.5.5 0 0 0 .78 0c.633-.79 1.814-1.019 3.222-.877 1.378.139 2.8.62 3.681 1.02A.5.5 0 0 0 16 13.5v-11a.5.5 0 0 0-.293-.455c-.952-.433-2.48-.952-3.994-1.105C10.413.809 8.985.936 8 1.783z"/>
                    </svg>
                </div>
            }
        </div>
    }
</div>

ThingsToReturn/Pages/Offers/Reserve.cshtml
@page
@model ThingsToReturn.Pages.ReserveOfferModel
@{
}
<div class="text-center">
    <form>
        <input hidden asp-for="Offer.Id" />
        <div class ="border p-3 mt-4">
            <div class="row pb-2">
                <h2 class="text-primary pl-3">Reserve advertisement</h2> 
                <hr />
            </div>
            <div class="mb-3">
                <label asp-for="Offer.Name"></label>
                <input asp-for="Offer.Name" disabled class="form-control"/>
            </div>               
            <div class="mb-3">  
                <label asp-for="Offer.Description" ></label>
                <input asp-for="Offer.Description" disabled class="form-control"/>
            </div>
            <div class="mb-3">  
                <label asp-for="Offer.CreatedDate" ></label>
                <input asp-for="Offer.CreatedDate" disabled class="form-control"/>
            </div>
            <div class="mb-3">  
                <label asp-for="Offer.ExpirationDate" ></label>
                <input asp-for="Offer.ExpirationDate" disabled class="form-control"/>
            </div>
            
            @*
             <div class="mb-3">  
                <label asp-for="" ></label>
                <input asp-for="" disabled class="form-control"/>
            </div>
            <div class="mb-3">  
                <label asp-for="" ></label>
                <input asp-for="" disabled class="form-control"/>
            </div>*@
        </div>
    </form>
</div>
    <hr/>
    @if(Model.Offer?.BookingId is not null)
    {
        <form method="post" asp-page-handler="Cancel" >
            <div class="user-reserve">
                 <input name="offerId" hidden class="form-control" value="@Model.Offer.Id" />
                 <div class="card-header" style="width: 75%">You already reservated your offer for @Model.Offer.BookingId</div>
                
                 <div style="margin-left: 10px">
                    <button type="submit" class="btn btn-danger">Cancel reservation</button>
                </div>
            </div>
        </form>

    }
    else
    {
        @foreach(var interested in Model.InterestedUsers.AppUsers)
        {
            <form method="post" asp-page-handler="Reserve" >
               <div class="user-reserve">
                    <div class="" style="width: 75%">
                        <input asp-for="Reservation.OfferId" hidden  class="form-control" value="@Model.Offer.Id" />
                        <input asp-for="Reservation.UserId" hidden  class="form-control" value="@interested.Id" />
                        <input asp-for="Reservation.UserName" disabled name="userName" class="form-control mb-2" value="@interested.UserName"/>
                    </div>
                    <div style="margin-left: 10px">
                        <button type="submit" class="btn btn-info">Reserve</button>
                    </div>
               </div>
            </form>
        }
    }